// Municipalités du Québec — sert à l'import Excel pour reconnaître la
// ville dans une adresse écrite d'un bloc, dans une colonne sans en-tête ou
// mal orthographiée (« st-jerome » → « Saint-Jérôme »). Liste tirée des
// données GeoNames, complétée à la main ; un nom absent ne fait que
// retomber sur le découpage par virgules. Côté serveur seulement (liste
// volumineuse) : ne pas l'importer dans un composant "use client".

const MUNICIPALITES = [
  "Abercorn", "Acton Vale", "Adstock", "Aguanish", "Ahuntsic-Cartierville", "Akwesasne", "Albanel",
  "Albertville", "Alleyn-et-Cawood", "Alma", "Amherst", "Amos", "Amqui", "Ange-Gardien", "Anjou",
  "Armagh", "Arntfield", "Arundel", "Asbestos", "Ascot Corner", "Aston-Jonction", "Audet", "Aumond",
  "Austin", "Authier", "Authier-Nord", "Ayer's Cliff", "Aylmer", "Baie-Comeau", "Baie-D'Urfé",
  "Baie-des-Sables", "Baie-du-Febvre", "Baie-James", "Baie-Johan-Beetz", "Baie-Saint-Paul",
  "Baie-Sainte-Catherine", "Baie-Trinité", "Barkmere", "Barnston-Ouest", "Barraute", "Batiscan",
  "Beaconsfield", "Béarn", "Beauceville", "Beauharnois", "Beaumont", "Beauport", "Beaupré",
  "Bécancour", "Bedford", "Bégin", "Belcourt", "Bellefeuille", "Belleterre", "Beloeil", "Berry",
  "Berthier-sur-Mer", "Berthierville", "Béthanie", "Betsiamites", "Black Lake", "Blainville",
  "Blanc-Sablon", "Blue Sea", "Bois-des-Filion", "Bois-Franc", "Boisbriand", "Boischatel",
  "Bolton-Est", "Bolton-Ouest", "Bonaventure", "Bonne-Espérance", "Bonsecours", "Boucherville",
  "Bouchette", "Bowman", "Breakeyville", "Brébeuf", "Brigham", "Bristol", "Bromont", "Brossard",
  "Brownsburg-Chatham", "Bryson", "Buckingham", "Buckland", "Bury", "Cabano", "Cacouna", "Cadillac",
  "Campbell's Bay", "Candiac", "Cantley", "Canton de Hatley", "Cap-aux-Meules", "Cap-Chat",
  "Cap-Rouge", "Cap-Saint-Ignace", "Cap-Santé", "Caplan", "Carignan", "Carillon", "Carleton",
  "Carleton-sur-Mer", "Cartierville", "Cascapédia–Saint-Jules", "Causapscal", "Chambly", "Chambord",
  "Champlain", "Champneuf", "Chandler", "Chapais", "Charette", "Charlemagne", "Charlesbourg",
  "Charny", "Chartierville", "Château-Richer", "Châteauguay", "Chazel", "Chelsea", "Chénéville",
  "Chertsey", "Chesterville", "Chibougamau", "Chichester", "Chicoutimi", "Chisasibi", "Chomedey",
  "Chute-aux-Outardes", "Chute-Saint-Philippe", "Cléricy", "Clermont", "Clerval", "Cleveland",
  "Cloridorme", "Coaticook", "Colombier", "Compton", "Contrecoeur", "Cookshire", "Cookshire-Eaton",
  "Côte-Nord-du-Golfe-du-Saint-Laurent", "Côte-Saint-Luc", "Coteau-du-Lac", "Courcelles",
  "Cowansville", "Crabtree", "Ct 0001", "Ct 0002", "Ct 0003", "Ct 0004", "Ct 0005", "Ct 0006",
  "Ct 0007", "Ct 0008", "Ct 0009", "Ct 0010", "Ct 0011", "Ct 0012", "Ct 0013", "Ct 0014", "Ct 0015",
  "Ct 0016", "Ct 0017", "Ct 0018", "Ct 0019", "Ct 0021", "Ct 0022", "Ct 0023", "Ct 0024", "Ct 0025",
  "Ct 0026", "Ct 0027", "Ct 0028", "Ct 0029", "Ct 0030", "Danville", "Daveluyville", "Dégelis",
  "Déléage", "Delson", "Desbiens", "Deschaillons-sur-Saint-Laurent", "Deschambault-Grondines",
  "Desmarchais-Crawford", "Deux-Montagnes", "Disraeli", "Dixville", "Dolbeau-Mistassini",
  "Dollard-Des Ormeaux", "Donnacona", "Dorval", "Dosquet", "Drummondville", "Dubuisson", "Dudswell",
  "Duhamel", "Dundee", "Dunham", "Duparquet", "Dupuy", "Durham-Sud", "Duvernay", "East Angus",
  "East Broughton", "East Hereford", "Eastman", "Eeyou Istchee Baie-James", "Egan-Sud", "Elgin",
  "Entrelacs", "Escuminac", "Esprit-Saint", "Essipit", "Estérel", "Évain", "Farnham", "Fassett",
  "Ferland-et-Boilleau", "Ferme-Neuve", "Fermont", "Fontainebleau", "Forestville", "Fort-Coulonge",
  "Fortierville", "Fossambault-sur-le-Lac", "Frampton", "Franklin", "Franquelin", "Frelighsburg",
  "Frontenac", "Fugèreville", "Gallichan", "Gaspé", "Gatineau", "Gentilly", "Girardville", "Godbout",
  "Godmanchester", "Gore", "Gould", "Gracefield", "Granby", "Grand-Mère", "Grand-Métis",
  "Grand-Remous", "Grand-Saint-Esprit", "Grande-Rivière", "Grande-Vallée", "Greenfield Park",
  "Grenville", "Grenville-sur-la-Rouge", "Gros-Mécatina", "Grosses-Roches", "Ham-Nord", "Ham-Sud",
  "Hampden", "Hampstead", "Harrington", "Hatley", "Hauterive", "Havelock", "Havre-Saint-Pierre",
  "Hébertville", "Hébertville-Station", "Hemmingford", "Henryville", "Hérouxville", "Honfleur",
  "Hope", "Hope Town", "Howick", "Huberdeau", "Hudson", "Hull", "Huntingdon", "Iberville",
  "Inukjuak", "Inverness", "Irlande", "Issoudun", "Ivry-sur-le-Lac", "Joliette", "Jonquière",
  "Kahnawake", "Kamouraska", "Kanesatake", "Kawawachikamach", "Kazabazua", "Kiamika", "Kingsbury",
  "Kingsey Falls", "Kinnear's Mills", "Kipawa", "Kirkland", "Knowlton", "Kuujjuaq",
  "L'Ancienne-Lorette", "L'Ange-Gardien", "L'Anse-Saint-Jean", "L'Ascension",
  "L'Ascension-de-Notre-Seigneur", "L'Ascension-de-Patapédia", "L'Assomption", "L'Avenir",
  "L'Épiphanie", "L'Île-Bizard–Sainte-Geneviève", "L'Île-Cadieux", "L'Île-Dorval", "L'Île-Perrot",
  "L'Isle-aux-Allumettes", "L'Isle-aux-Coudres", "L'Isle-Verte", "L'Islet", "L'Islet-sur-Mer",
  "La Baie", "La Cité-Limoilou", "La Conception", "La Doré", "La Durantaye", "La Guadeloupe",
  "La Haute-Saint-Charles", "La Malbaie", "La Minerve", "La Morandière", "La Motte", "La Patrie",
  "La Pêche", "La Pocatière", "La Prairie", "La Présentation", "La Reine", "La Sarre",
  "La Trinité-des-Monts", "La Tuque", "La Visitation-de-l'Île-Dupas", "La Visitation-de-Yamaska",
  "Labelle", "Lac-à-la-Tortue", "Lac-au-Saumon", "Lac-Beauport", "Lac-Bouchette", "Lac-Brome",
  "Lac-Delage", "Lac-des-Aigles", "Lac-des-Écorces", "Lac-des-Plages", "Lac-Etchemin",
  "Lac-Frontière", "Lac-Mégantic", "Lac-Nominingue", "Lac-Saguay", "Lac-Saint-Joseph",
  "Lac-Sainte-Marie", "Lac-Sergent", "Lac-Simon", "Lac-Supérieur", "Lac-Tremblant-Nord", "Lachine",
  "Lachute", "Lacolle", "Laflèche", "Lafontaine", "Lamarche", "Lambton", "Landrienne", "Laniel",
  "Lanoraie", "Lantier", "Larouche", "LaSalle", "Laterrière", "Latulipe-et-Gaboury", "Launay",
  "Laurier-Station", "Laurierville", "Laval", "Laval-des-Rapides", "Lavaltrie",
  "Laverlochère-Angliers", "Lawrenceville", "Le Bic", "Le Moyne", "Le Plateau-Mont-Royal",
  "Le Sud-Ouest", "Le Vieux-Longueuil", "Lebel-sur-Quévillon", "Leblanc", "Leclercville", "Leeds",
  "Lemieux", "Lennoxville", "Léry", "Les Bergeronnes", "Les Cèdres", "Les Coteaux",
  "Les Éboulements", "Les Escoumins", "Les Hauteurs", "Les Îles-de-la-Madeleine", "Les Méchins",
  "Lévis", "Lingwick", "Linière", "Listuguj", "Litchfield", "Lochaber", "Longue-Pointe-de-Mingan",
  "Longue-Rive", "Longueuil", "Loretteville", "Lorraine", "Lorrainville", "Lotbinière",
  "Louiseville", "Low", "Luceville", "Lyster", "Macamic", "Magog", "Malartic", "Maliotenam",
  "Manawan", "Mandeville", "Maniwaki", "Manseau", "Mansfield-et-Pontefract", "Mansonville", "Maria",
  "Maricourt", "Marieville", "Marsoui", "Marston", "Mascouche", "Mashteuiatsh", "Maskinongé",
  "Massueville", "Matagami", "Matane", "Matapédia", "Mayo", "McMasterville", "Melbourne",
  "Melocheville", "Mercier", "Mercier–Hochelaga-Maisonneuve", "Messines", "Métabetchouan",
  "Métis-sur-Mer", "Milan", "Mille-Isles", "Mirabel", "Mistissini", "Moffet", "Mont-Carmel",
  "Mont-Joli", "Mont-Laurier", "Mont-Lebel", "Mont-Royal", "Mont-Saint-Grégoire",
  "Mont-Saint-Hilaire", "Mont-Saint-Pierre", "Mont-Tremblant", "Montcalm", "Montcerf-Lytton",
  "Montebello", "Montmagny", "Montréal", "Montréal-Est", "Montréal-Nord", "Montréal-Ouest",
  "Morin-Heights", "Mulgrave-et-Derry", "Murdochville", "Nantes", "Napierville", "Natashquan",
  "Nédélec", "Neuville", "New Carlisle", "New-Richmond", "Nicolet", "Nominingue", "Normandin",
  "Normétal", "North Hatley", "Notre-Dame-de-Grâce", "Notre-Dame-de-l'Île-Perrot",
  "Notre-Dame-de-la-Merci", "Notre-Dame-de-la-Paix", "Notre-Dame-de-Lorette",
  "Notre-Dame-de-Pontmain", "Notre-Dame-de-Stanbridge", "Notre-Dame-des-Bois",
  "Notre-Dame-des-Monts", "Notre-Dame-des-Pins", "Notre-Dame-des-Prairies",
  "Notre-Dame-des-Sept-Douleurs", "Notre-Dame-du-Bon-Conseil", "Notre-Dame-du-Lac",
  "Notre-Dame-du-Laus", "Notre-Dame-du-Mont-Carmel", "Notre-Dame-du-Nord", "Notre-Dame-du-Portage",
  "Notre-Dame-du-Rosaire", "Nouvelle", "Noyan", "Odanak", "Ogden", "Oka", "Orford", "Ormstown",
  "Otter Lake", "Otterburn Park", "Outremont", "Padoue", "Palmarolle", "Papineauville",
  "Parc-Extension", "Parisville", "Paspébiac", "Percé", "Péribonka", "Pessamit", "Petit-Saguenay",
  "Petite-Rivière-Saint-François", "Petite-Vallée", "Piedmont", "Pierrefonds", "Pierrefonds-Roxboro",
  "Pierreville", "Pike River", "Pincourt", "Pintendre", "Piopolis", "Plaisance", "Plessisville",
  "Pohénégamook", "Pointe-à-la-Croix", "Pointe-aux-Outardes", "Pointe-aux-Trembles",
  "Pointe-Calumet", "Pointe-Claire", "Pointe-des-Cascades", "Pointe-du-Lac", "Pointe-Fortune",
  "Pointe-Lebel", "Pointe-Saint-Charles", "Pont-Rouge", "Pont-Viau", "Pontiac", "Port-Cartier",
  "Port-Daniel–Gascons", "Portneuf", "Portneuf-sur-Mer", "Potton", "Poularies", "Preissac",
  "Prévost", "Price", "Princeville", "Puvirnituq", "Québec", "Racine", "Radisson", "Ragueneau",
  "Rapide-Danseur", "Rawdon", "Rémigny", "Repentigny", "Richelieu", "Richmond", "Rigaud", "Rimouski",
  "Ripon", "Ristigouche-Partie-Sud-Est", "Rivière-à-Claude", "Rivière-à-Pierre",
  "Rivière-au-Tonnerre", "Rivière-Beaudette", "Rivière-des-Prairies",
  "Rivière-des-Prairies–Pointe-aux-Trembles", "Rivière-du-Loup", "Rivière-Éternité", "Rivière-Héva",
  "Rivière-Ouelle", "Rivière-Rouge", "Rivière-Saint-Jean", "Roberval", "Rochebaucourt",
  "Rock Forest", "Rollet", "Roquemaure", "Rosemère", "Rosemont–La Petite-Patrie", "Rougemont",
  "Rouyn-Noranda", "Roxboro", "Roxton Falls", "Roxton Pond", "Sacré-Coeur", "Sacré-Coeur-de-Jésus",
  "Saguenay", "Saint-Adelme", "Saint-Adelphe", "Saint-Adolphe-d'Howard", "Saint-Adrien",
  "Saint-Agapit", "Saint-Aimé", "Saint-Aimé-des-Lacs", "Saint-Alban", "Saint-Alexandre",
  "Saint-Alexandre-de-Kamouraska", "Saint-Alexandre-des-Lacs", "Saint-Alexis-de-Matapédia",
  "Saint-Alexis-des-Monts", "Saint-Alfred", "Saint-Alphonse-de-Granby", "Saint-Alphonse-Rodriguez",
  "Saint-Amable", "Saint-Ambroise", "Saint-Ambroise-de-Kildare", "Saint-Anaclet-de-Lessard",
  "Saint-André-Avellin", "Saint-André-d'Argenteuil", "Saint-André-de-Kamouraska",
  "Saint-André-de-Restigouche", "Saint-André-Est", "Saint-Anicet", "Saint-Anselme",
  "Saint-Antoine-de-Tilly", "Saint-Antoine-sur-Richelieu", "Saint-Antonin", "Saint-Apollinaire",
  "Saint-Armand", "Saint-Arsène", "Saint-Aubert", "Saint-Augustin", "Saint-Augustin-de-Desmaures",
  "Saint-Augustin-de-Woburn", "Saint-Barnabé-Sud", "Saint-Barthélemy", "Saint-Basile",
  "Saint-Basile-le-Grand", "Saint-Benoît-du-Lac", "Saint-Benoît-Labre", "Saint-Bernard-de-Lacolle",
  "Saint-Blaise-sur-Richelieu", "Saint-Bonaventure", "Saint-Boniface", "Saint-Bruno",
  "Saint-Bruno-de-Guigues", "Saint-Bruno-de-Kamouraska", "Saint-Bruno-de-Montarville",
  "Saint-Calixte", "Saint-Camille", "Saint-Camille-de-Lellis", "Saint-Canut", "Saint-Casimir",
  "Saint-Célestin", "Saint-Césaire", "Saint-Charles-Borromée", "Saint-Charles-de-Bellechasse",
  "Saint-Charles-de-Bourget", "Saint-Charles-sur-Richelieu", "Saint-Christophe-d'Arthabaska",
  "Saint-Chrysostome", "Saint-Clément", "Saint-Cléophas", "Saint-Cléophas-de-Brandon", "Saint-Clet",
  "Saint-Colomban", "Saint-Côme-Linière", "Saint-Constant", "Saint-Cuthbert",
  "Saint-Cyprien-de-Napierville", "Saint-Cyrille-de-Wendover", "Saint-Damase",
  "Saint-Damase-de-L'Islet", "Saint-Damien-de-Buckland", "Saint-David-de-Falardeau",
  "Saint-Denis-de-Brompton", "Saint-Denis-De La Bouteillerie", "Saint-Denis-sur-Richelieu",
  "Saint-Didace", "Saint-Dominique", "Saint-Dominique-du-Rosaire", "Saint-Donat",
  "Saint-Donat-de-Montcalm", "Saint-Edmond-les-Plaines", "Saint-Édouard-de-Lotbinière",
  "Saint-Élie-de-Caxton", "Saint-Éloi", "Saint-Elphège", "Saint-Elzéar", "Saint-Elzéar-de-Beauce",
  "Saint-Éphrem-de-Beauce", "Saint-Épiphane", "Saint-Esprit", "Saint-Étienne-de-Beauharnois",
  "Saint-Étienne-des-Grès", "Saint-Eugène-d'Argentenay", "Saint-Eugène-de-Guigues", "Saint-Eustache",
  "Saint-Évariste-de-Forsyth", "Saint-Fabien", "Saint-Fabien-de-Panet", "Saint-Félicien",
  "Saint-Félix-d'Otis", "Saint-Félix-de-Dalquier", "Saint-Félix-de-Valois", "Saint-Ferdinand",
  "Saint-Ferréol-les-Neiges", "Saint-Flavien", "Saint-Fortunat", "Saint-François-d'Assise",
  "Saint-François-de-l'Île-d'Orléans", "Saint-François-de-la-Rivière-du-Sud",
  "Saint-François-de-Sales", "Saint-François-du-Lac", "Saint-François-Xavier-de-Brompton",
  "Saint-François-Xavier-de-Viger", "Saint-Frédéric", "Saint-Fulgence", "Saint-Gabriel-de-Brandon",
  "Saint-Gabriel-de-Rimouski", "Saint-Gabriel-de-Valcartier", "Saint-Gabriel-Lalemant",
  "Saint-Gédéon", "Saint-Gédéon-de-Beauce", "Saint-Georges", "Saint-Georges-de-Windsor",
  "Saint-Gérard", "Saint-Germain-de-Grantham", "Saint-Gervais", "Saint-Gilles", "Saint-Guillaume",
  "Saint-Guy", "Saint-Henri", "Saint-Henri-de-Taillon", "Saint-Hermas", "Saint-Herménégilde",
  "Saint-Hilaire-de-Dorset", "Saint-Hilarion", "Saint-Hippolyte", "Saint-Honoré",
  "Saint-Honoré-de-Shenley", "Saint-Hubert", "Saint-Hubert-de-Rivière-du-Loup", "Saint-Hugues",
  "Saint-Hyacinthe", "Saint-Ignace-de-Loyola", "Saint-Ignace-de-Stanbridge", "Saint-Irénée",
  "Saint-Isidore", "Saint-Isidore-de-Clifton", "Saint-Isidore-de-Laprairie", "Saint-Jacques",
  "Saint-Jacques-de-Leeds", "Saint-Jacques-le-Mineur", "Saint-Janvier-de-Joly",
  "Saint-Jean-Baptiste", "Saint-Jean-Chrysostome", "Saint-Jean-de-Brébeuf",
  "Saint-Jean-de-Cherbourg", "Saint-Jean-de-Dieu", "Saint-Jean-de-l'Île-d'Orléans",
  "Saint-Jean-de-Matha", "Saint-Jean-sur-Richelieu", "Saint-Jérôme", "Saint-Joachim",
  "Saint-Joachim-de-Shefford", "Saint-Joseph-de-Beauce", "Saint-Joseph-de-Coleraine",
  "Saint-Joseph-de-Kamouraska", "Saint-Joseph-de-Sorel", "Saint-Joseph-des-Érables",
  "Saint-Joseph-du-Lac", "Saint-Jude", "Saint-Just-de-Bretenières", "Saint-Lambert",
  "Saint-Lambert-de-Lauzon", "Saint-Laurent", "Saint-Laurent-de-l'Île-d'Orléans", "Saint-Lazare",
  "Saint-Lazare-de-Bellechasse", "Saint-Léandre", "Saint-Léon-de-Standon", "Saint-Léon-le-Grand",
  "Saint-Léonard", "Saint-Léonard-d'Aston", "Saint-Léonard-de-Portneuf", "Saint-Liboire",
  "Saint-Liguori", "Saint-Lin-Laurentides", "Saint-Louis-de-Blandford", "Saint-Louis-de-Gonzague",
  "Saint-Louis-de-Gonzague-du-Cap-Tourmente", "Saint-Louis-de-Terrebonne", "Saint-Louis-du-Ha Ha",
  "Saint-Luc-de-Bellechasse", "Saint-Luc-de-Vincennes", "Saint-Lucien", "Saint-Ludger",
  "Saint-Ludger-de-Milot", "Saint-Magloire", "Saint-Majorique-de-Grantham", "Saint-Malachie",
  "Saint-Malo", "Saint-Marc-de-Figuery", "Saint-Marc-des-Carrières", "Saint-Marc-sur-Richelieu",
  "Saint-Marcel-de-Richelieu", "Saint-Martin", "Saint-Mathieu-d'Harricana",
  "Saint-Mathieu-de-Beloeil", "Saint-Mathieu-de-Rioux", "Saint-Mathieu-du-Parc", "Saint-Maurice",
  "Saint-Médard", "Saint-Méthode-de-Frontenac", "Saint-Michel", "Saint-Michel-de-Bellechasse",
  "Saint-Michel-des-Saints", "Saint-Modeste", "Saint-Moïse", "Saint-Narcisse",
  "Saint-Narcisse-de-Beaurivage", "Saint-Narcisse-de-Rimouski", "Saint-Nazaire",
  "Saint-Nazaire-d'Acton", "Saint-Nérée-de-Bellechasse", "Saint-Nicolas", "Saint-Noël",
  "Saint-Norbert", "Saint-Norbert-d'Arthabaska", "Saint-Octave-de-Métis",
  "Saint-Odilon-de-Cranbourne", "Saint-Omer", "Saint-Onésime-d'Ixworth", "Saint-Ours",
  "Saint-Pacôme", "Saint-Pamphile", "Saint-Pascal", "Saint-Patrice-de-Beaurivage",
  "Saint-Patrice-de-Sherrington", "Saint-Paul-d'Abbotsford", "Saint-Paul-de-la-Croix",
  "Saint-Paul-de-Montminy", "Saint-Paulin", "Saint-Philémon", "Saint-Philibert", "Saint-Philippe",
  "Saint-Philippe-de-La Prairie", "Saint-Pie", "Saint-Pie-de-Guire", "Saint-Pierre-Baptiste",
  "Saint-Pierre-de-Broughton", "Saint-Pierre-de-l'Île-d'Orléans",
  "Saint-Pierre-de-la-Rivière-du-Sud", "Saint-Pierre-les-Becquets", "Saint-Placide",
  "Saint-Polycarpe", "Saint-Prime", "Saint-Prosper", "Saint-Prosper-de-Champlain", "Saint-Raphaël",
  "Saint-Raymond", "Saint-Rédempteur", "Saint-Rémi", "Saint-Rémi-de-Tingwick", "Saint-René",
  "Saint-René-de-Matane", "Saint-Robert-Bellarmin", "Saint-Roch-de-l'Achigan",
  "Saint-Roch-de-Richelieu", "Saint-Roch-des-Aulnaies", "Saint-Rosaire", "Saint-Samuel",
  "Saint-Sauveur", "Saint-Sauveur-des-Monts", "Saint-Siméon", "Saint-Simon-de-Rimouski",
  "Saint-Simon-les-Mines", "Saint-Sixte", "Saint-Stanislas-de-Kostka", "Saint-Sulpice",
  "Saint-Sylvère", "Saint-Sylvestre", "Saint-Télesphore", "Saint-Tharcisius",
  "Saint-Théodore-d'Acton", "Saint-Thomas", "Saint-Thomas-Didyme", "Saint-Thuribe", "Saint-Timothée",
  "Saint-Tite", "Saint-Tite-des-Caps", "Saint-Ubalde", "Saint-Ulric", "Saint-Urbain",
  "Saint-Urbain-Premier", "Saint-Valentin", "Saint-Valère", "Saint-Valérien-de-Milton",
  "Saint-Vallier", "Saint-Venant-de-Paquette", "Saint-Vianney", "Saint-Viateur", "Saint-Victor",
  "Saint-Vincent-de-Paul", "Saint-Wenceslas", "Saint-Zacharie", "Saint-Zénon",
  "Saint-Zéphirin-de-Courval", "Saint-Zotique", "Sainte-Adèle", "Sainte-Agathe-de-Lotbinière",
  "Sainte-Agathe-des-Monts", "Sainte-Angèle-de-Mérici", "Sainte-Angèle-de-Monnoir",
  "Sainte-Anne-de-Beaupré", "Sainte-Anne-de-Bellevue", "Sainte-Anne-de-la-Pérade",
  "Sainte-Anne-de-la-Pocatière", "Sainte-Anne-de-Sabrevois", "Sainte-Anne-de-Sorel",
  "Sainte-Anne-des-Monts", "Sainte-Anne-des-Plaines", "Sainte-Anne-du-Lac",
  "Sainte-Apolline-de-Patton", "Sainte-Aurélie", "Sainte-Barbe", "Sainte-Béatrix",
  "Sainte-Brigitte-de-Laval", "Sainte-Brigitte-des-Saults", "Sainte-Catherine",
  "Sainte-Catherine-de-Hatley", "Sainte-Catherine-de-la-Jacques-Cartier", "Sainte-Cécile-de-Milton",
  "Sainte-Cécile-de-Whitton", "Sainte-Christine-d'Auvergne", "Sainte-Claire", "Sainte-Clotilde",
  "Sainte-Clotilde-de-Beauce", "Sainte-Clotilde-de-Horton", "Sainte-Croix", "Sainte-Élisabeth",
  "Sainte-Émélie-de-l'Énergie", "Sainte-Eulalie", "Sainte-Famille", "Sainte-Félicité",
  "Sainte-Flavie", "Sainte-Florence", "Sainte-Foy", "Sainte-Foy–Sillery–Cap-Rouge",
  "Sainte-Geneviève-de-Batiscan", "Sainte-Geneviève-de-Berthier", "Sainte-Germaine-Boulé",
  "Sainte-Hedwidge", "Sainte-Hélène-de-Bagot", "Sainte-Hélène-de-Chester",
  "Sainte-Hélène-de-Mancebourg", "Sainte-Hénédine", "Sainte-Irène", "Sainte-Jeanne-d'Arc",
  "Sainte-Julie", "Sainte-Julienne", "Sainte-Justine", "Sainte-Justine-de-Newton", "Sainte-Louise",
  "Sainte-Luce", "Sainte-Lucie-de-Beauregard", "Sainte-Lucie-des-Laurentides", "Sainte-Madeleine",
  "Sainte-Madeleine-de-la-Rivière-Madeleine", "Sainte-Marcelline-de-Kildare",
  "Sainte-Marguerite-du-Lac-Masson", "Sainte-Marie", "Sainte-Marie-de-Beauce", "Sainte-Marie-Salomé",
  "Sainte-Marthe", "Sainte-Marthe-sur-le-Lac", "Sainte-Martine", "Sainte-Mélanie", "Sainte-Monique",
  "Sainte-Paule", "Sainte-Perpétue", "Sainte-Pétronille", "Sainte-Praxède", "Sainte-Rita",
  "Sainte-Rose-de-Watford", "Sainte-Rose-du-Nord", "Sainte-Sabine", "Sainte-Scholastique",
  "Sainte-Sophie", "Sainte-Sophie-de-Lévrard", "Sainte-Thècle", "Sainte-Thérèse",
  "Saints-Martyrs-Canadiens", "Salaberry-de-Valleyfield", "Salluit", "Sayabec", "Schefferville",
  "Scotstown", "Scott", "Senneterre", "Senneville", "Sept-Îles", "Shannon", "Shawinigan",
  "Shawville", "Shefford", "Sherbrooke", "Shigawake", "Shipshaw", "Sillery", "Snowdon",
  "Sorel-Tracy", "Stanbridge East", "Stanstead", "Stanstead-Est", "Stoke", "Stoneham-et-Tewkesbury",
  "Stornoway", "Stukely", "Stukely-Sud", "Sullivan", "Sutton", "Tadoussac", "Taschereau",
  "Témiscaming", "Témiscouata-sur-le-Lac", "Templeton-Est", "Terrasse-Vaudreuil", "Terrebonne",
  "Thetford-Mines", "Thurso", "Tingwick", "Tourville", "Trécesson", "Très-Saint-Rédempteur",
  "Très-Saint-Sacrement", "Tring-Jonction", "Trois-Rivières", "Uashat", "Ulverton", "Upton",
  "Val-Alain", "Val-Bélair", "Val-Brillant", "Val-d'Or", "Val-David", "Val-des-Bois", "Val-des-Lacs",
  "Val-des-Monts", "Val-des-Sources", "Val-Joli", "Val-Morin", "Val-Racine", "Val-Senneville",
  "Valcourt", "Vallée-Jonction", "Vanier", "Varennes", "Vaudreuil-Dorion", "Vaudreuil-sur-le-Lac",
  "Venise-en-Québec", "Verchères", "Verdun", "Victoriaville", "Vieux-Montréal", "Ville-Émard",
  "Ville-Marie", "Villeray–Saint-Michel–Parc-Extension", "Villeroy", "Wakefield", "Waltham",
  "Warden", "Warwick", "Waskaganish", "Waswanipi", "Waterloo", "Waterville", "Weedon", "Wendake",
  "Wentworth", "Wentworth-Nord", "Westmount", "Weymontachie", "Wickham", "Windsor", "Woburn",
  "Wotton", "Yamachiche", "Yamaska",
];

// Clé de comparaison : sans accents, casse ni ponctuation, abréviations
// courantes développées (« St-Jean » = « Saint-Jean », « Ste » = « Sainte »).
const ABREVIATIONS = { st: "saint", ste: "sainte", sts: "saints", mt: "mont", n: "nord", s: "sud", e: "est", o: "ouest" };
function cleVille(texte) {
  return String(texte || "")
    .normalize("NFD").replace(/[\u0300-\u036f]/g, "")
    .toLowerCase().replace(/[^a-z0-9]+/g, " ").trim()
    .split(" ").map((m) => ABREVIATIONS[m] || m).join(" ");
}

const PAR_CLE = new Map(MUNICIPALITES.map((nom) => [cleVille(nom), nom]));
const MOTS_MAX = Math.max(...MUNICIPALITES.map((nom) => cleVille(nom).split(" ").length));

// Nom officiel d'une municipalité écrite librement, ou null si inconnue
function trouverMunicipalite(texte) {
  const cle = cleVille(texte);
  return (cle && PAR_CLE.get(cle)) || null;
}

// Mots qui annoncent un nom de rue : une « ville » juste après fait partie
// du nom de la rue (« 12 rue Saint-Laurent », « 4 boul. de Mortagne »).
const MOTS_DE_RUE = new Set([
  "rue", "r", "avenue", "av", "ave", "boulevard", "boul", "bd", "blvd", "chemin", "ch", "route", "rte", "rang", "rg",
  "montee", "mtee", "cote", "place", "pl", "croissant", "crois", "impasse", "allee", "terrasse", "promenade", "carre",
  "square", "parc", "cour", "voie", "autoroute", "street", "st", "road", "rd", "drive", "dr", "lane", "way", "court",
  "de", "du", "des", "la", "le", "les", "l", "d", "of", "the",
]);

// Ville collée à la fin d'une adresse, sans virgule (« 12 rue Principale
// Saint-Jérôme ») → { adresse: "12 rue Principale", ville: "Saint-Jérôme" },
// ou null. Il doit rester devant une adresse plausible (au moins deux mots,
// dont un numéro) qui ne se termine pas par « rue », « boul. », « de »…
function separerVilleEnFin(texte) {
  const mots = String(texte || "").trim().split(/\s+/);
  for (let n = Math.min(MOTS_MAX, mots.length - 2); n >= 1; n--) {
    const ville = trouverMunicipalite(mots.slice(-n).join(" "));
    if (!ville) continue;
    const avant = mots.slice(0, -n);
    const dernier = cleVille(avant[avant.length - 1]);
    if (MOTS_DE_RUE.has(dernier) || !avant.some((m) => /\d/.test(m))) continue;
    return { adresse: avant.join(" ").replace(/[\s,]+$/, ""), ville };
  }
  return null;
}

module.exports = { MUNICIPALITES, cleVille, trouverMunicipalite, separerVilleEnFin };
