// Versions (niveaux de finition) proposées dans la 4e liste déroulante du
// dossier véhicule. Le catalogue NHTSA (lib/catalogueVehicules.json) ne
// contient que l'année, la marque et le modèle — les versions viennent
// d'ici : la liste des versions connues pour les modèles courants au
// Québec, sinon celles typiques de la marque, sinon une liste générale.
// La liste reste ouverte : « Autre… » permet toujours d'entrer une version
// qui n'y figure pas, et le décodage du NIV peut en fournir une.
//
// Clés : marque telle qu'écrite dans le catalogue (majuscules NHTSA) et
// nom de modèle exact du catalogue.

const VERSIONS_PAR_MODELE = {
  ACURA: {
    ILX: ["Base", "Premium", "Tech", "A-Spec"],
    Integra: ["Base", "A-Spec", "A-Spec Tech", "Type S"],
    MDX: ["Base", "Tech", "A-Spec", "Platinum Elite", "Type S", "Type S Ultra"],
    RDX: ["Base", "Tech", "A-Spec", "Platinum Elite", "Elite A-Spec"],
    TLX: ["Base", "Tech", "A-Spec", "Platinum Elite", "Type S"],
    TSX: ["Base", "Premium", "Tech"],
  },
  BUICK: {
    Enclave: ["Essence", "Premium", "Avenir"],
    Encore: ["Base", "Preferred", "Sport Touring", "Essence"],
    "Encore GX": ["Preferred", "Select", "Sport Touring", "Essence", "Avenir"],
    Envision: ["Preferred", "Essence", "Avenir"],
    Envista: ["Preferred", "Sport Touring", "Avenir"],
  },
  CHEVROLET: {
    Blazer: ["LT", "RS", "Premier", "2LT", "3LT"],
    "Bolt EV": ["LT", "1LT", "2LT", "Premier"],
    "Bolt EUV": ["LT", "Premier"],
    Camaro: ["1LT", "2LT", "3LT", "1SS", "2SS", "ZL1"],
    Colorado: ["WT", "LT", "Z71", "Trail Boss", "ZR2"],
    Corvette: ["1LT", "2LT", "3LT", "Z06", "E-Ray", "ZR1"],
    Cruze: ["L", "LS", "LT", "Premier", "Diesel"],
    Equinox: ["LS", "LT", "RS", "Premier", "ACTIV"],
    Express: ["2500", "3500", "Cargo", "Passenger LS", "Passenger LT"],
    Malibu: ["L", "LS", "RS", "LT", "2LT", "Premier"],
    Silverado: ["WT", "Custom", "Custom Trail Boss", "LT", "RST", "LT Trail Boss", "LTZ", "High Country", "ZR2"],
    "Silverado HD": ["WT", "Custom", "LT", "LTZ", "High Country", "ZR2"],
    Sonic: ["LS", "LT", "Premier"],
    Spark: ["LS", "1LT", "2LT", "ACTIV"],
    Suburban: ["LS", "LT", "RST", "Z71", "Premier", "High Country"],
    Tahoe: ["LS", "LT", "RST", "Z71", "Premier", "High Country"],
    Trailblazer: ["LS", "LT", "ACTIV", "RS"],
    Traverse: ["LS", "LT", "RS", "Premier", "High Country", "Z71"],
    Trax: ["LS", "1RS", "LT", "2RS", "ACTIV"],
    Volt: ["LT", "Premier"],
  },
  CHRYSLER: {
    300: ["Touring", "Touring L", "S", "300C", "Limited"],
    Pacifica: ["Touring", "Touring L", "Limited", "Pinnacle", "Hybrid"],
    "Grand Caravan": ["SXT", "Canada Value Package", "Crew", "Crew Plus"],
    "Town and Country": ["Touring", "Touring-L", "Limited", "Limited Platinum"],
  },
  DODGE: {
    Challenger: ["SXT", "GT", "R/T", "R/T Scat Pack", "SRT Hellcat", "SRT Demon"],
    Charger: ["SXT", "GT", "R/T", "Scat Pack", "SRT Hellcat", "Daytona"],
    Durango: ["SXT", "GT", "R/T", "Citadel", "SRT 392", "SRT Hellcat"],
    "Grand Caravan": ["SE", "SXT", "Canada Value Package", "Crew", "Crew Plus", "GT"],
    Hornet: ["GT", "GT Plus", "R/T", "R/T Plus"],
    Journey: ["Canada Value Package", "SE", "SXT", "Crossroad", "R/T", "GT"],
  },
  FORD: {
    Bronco: ["Base", "Big Bend", "Black Diamond", "Outer Banks", "Badlands", "Wildtrak", "Everglades", "Raptor"],
    "Bronco Sport": ["Base", "Big Bend", "Outer Banks", "Badlands", "Heritage"],
    Ecosport: ["S", "SE", "SES", "Titanium"],
    Edge: ["SE", "SEL", "ST-Line", "Titanium", "ST"],
    Escape: ["S", "SE", "SEL", "Active", "ST-Line", "Platinum", "Titanium", "Hybrid", "PHEV"],
    Expedition: ["XL", "XLT", "Limited", "King Ranch", "Platinum", "Timberline", "Tremor"],
    "Expedition MAX": ["XLT", "Limited", "King Ranch", "Platinum"],
    Explorer: ["Base", "XLT", "Limited", "ST-Line", "Timberline", "King Ranch", "Platinum", "ST"],
    "F-150": ["XL", "XLT", "Lariat", "King Ranch", "Platinum", "Limited", "Tremor", "Raptor", "Lightning Pro", "Lightning XLT", "Lightning Lariat", "Lightning Platinum"],
    "F-250": ["XL", "XLT", "Lariat", "King Ranch", "Platinum", "Limited", "Tremor"],
    "F-350": ["XL", "XLT", "Lariat", "King Ranch", "Platinum", "Limited", "Tremor"],
    Fiesta: ["S", "SE", "Titanium", "ST"],
    Flex: ["SE", "SEL", "Limited"],
    Focus: ["S", "SE", "SEL", "Titanium", "ST", "RS", "Electric"],
    Fusion: ["S", "SE", "SEL", "Titanium", "Sport", "Hybrid", "Energi"],
    Maverick: ["XL", "XLT", "Lariat", "Tremor", "Lobo"],
    "Mustang Mach-E": ["Select", "Premium", "California Route 1", "GT", "Rally"],
    Mustang: ["EcoBoost", "EcoBoost Premium", "GT", "GT Premium", "Mach 1", "Dark Horse", "Shelby GT350", "Shelby GT500"],
    Ranger: ["XL", "XLT", "Lariat", "Raptor"],
    Transit: ["Cargo", "Crew", "Passenger XL", "Passenger XLT", "Trail"],
    "Transit Connect": ["XL", "XLT", "Titanium"],
  },
  GMC: {
    Acadia: ["SLE", "SLT", "AT4", "Denali", "Elevation"],
    Canyon: ["Elevation", "AT4", "Denali", "AT4X", "SLE", "SLT"],
    Savana: ["2500", "3500", "Cargo", "Passenger LS", "Passenger LT"],
    Sierra: ["Pro", "SLE", "Elevation", "SLT", "AT4", "Denali", "Denali Ultimate", "AT4X"],
    "Sierra HD": ["Pro", "SLE", "SLT", "AT4", "Denali", "Denali Ultimate"],
    Terrain: ["SLE", "SLT", "AT4", "Denali", "Elevation"],
    Yukon: ["SLE", "SLT", "AT4", "Denali", "Denali Ultimate"],
    "Yukon XL": ["SLE", "SLT", "AT4", "Denali", "Denali Ultimate"],
  },
  HONDA: {
    Accord: ["LX", "EX", "EX-L", "Sport", "Sport-L", "Touring", "Hybrid"],
    Civic: ["DX", "LX", "EX", "EX-L", "Sport", "Sport Touring", "Touring", "Hybrid", "Si", "Type R"],
    "Civic Si": ["Base", "HFP"],
    "Civic Type R": ["Base"],
    "CR-V": ["LX", "EX", "EX-L", "Sport", "Sport-L", "Touring", "Black Edition", "Hybrid"],
    Fit: ["DX", "LX", "Sport", "EX", "EX-L", "Sport", "Touring"],
    "HR-V": ["LX", "Sport", "EX", "EX-L", "Touring"],
    Insight: ["LX", "EX", "Touring"],
    Odyssey: ["LX", "EX", "EX-RES", "EX-L", "Black Edition", "Touring"],
    Passport: ["Sport", "EX-L", "TrailSport", "Touring", "Black Edition"],
    Pilot: ["LX", "Sport", "EX", "EX-L", "TrailSport", "Touring", "Black Edition"],
    Prologue: ["EX", "Touring"],
    Ridgeline: ["Sport", "EX-L", "Touring", "TrailSport", "Black Edition"],
  },
  HYUNDAI: {
    Accent: ["L", "GL", "GLS", "SE", "Preferred", "Ultimate"],
    Elantra: ["Essential", "Preferred", "Luxury", "Ultimate", "N Line", "Hybrid", "GL", "GLS", "Limited", "Sport"],
    "Elantra GT": ["GL", "GLS", "SE", "Preferred", "Luxury", "Sport", "N Line"],
    "Elantra N": ["Base"],
    "Ioniq 5": ["Preferred", "Preferred Long Range", "Ultimate", "N Line", "XRT", "N"],
    "Ioniq 6": ["Preferred", "Preferred Long Range", "Ultimate"],
    Kona: ["Essential", "Preferred", "Trend", "Luxury", "Ultimate", "N Line", "N", "Electric"],
    Palisade: ["Essential", "Preferred", "Luxury", "Ultimate Calligraphy", "Urbane", "XRT"],
    "Santa Cruz": ["Preferred", "Trend", "Ultimate", "XRT"],
    "Santa Fe": ["Essential", "Preferred", "Luxury", "Ultimate Calligraphy", "XRT", "Hybrid", "GL", "GLS", "Limited", "SE"],
    "Santa Fe Sport": ["Base", "Premium", "Luxury", "SE", "Limited"],
    "Santa Fe XL": ["Premium", "Luxury", "Limited", "Ultimate"],
    Sonata: ["GL", "GLS", "Preferred", "Luxury", "Sport", "Ultimate", "N Line", "Hybrid"],
    Tucson: ["Essential", "Preferred", "Trend", "Luxury", "Ultimate", "N Line", "Hybrid", "Plug-in Hybrid", "GL", "GLS", "Limited"],
    Veloster: ["Base", "Tech", "Turbo", "Turbo Tech", "N"],
    Venue: ["Essential", "Preferred", "Trend", "Ultimate"],
  },
  JEEP: {
    Cherokee: ["Sport", "North", "Altitude", "Latitude", "Limited", "Trailhawk", "Overland"],
    Compass: ["Sport", "North", "Altitude", "Latitude", "Limited", "Trailhawk"],
    Gladiator: ["Sport", "Sport S", "Willys", "Overland", "Rubicon", "Mojave"],
    "Grand Cherokee": ["Laredo", "Altitude", "Limited", "Trailhawk", "Overland", "Summit", "Summit Reserve", "SRT", "Trackhawk", "4xe"],
    "Grand Cherokee L": ["Laredo", "Altitude", "Limited", "Overland", "Summit", "Summit Reserve"],
    Patriot: ["Sport", "North", "High Altitude", "Limited"],
    Renegade: ["Sport", "North", "Altitude", "Limited", "Trailhawk"],
    Wrangler: ["Sport", "Sport S", "Willys", "Sahara", "High Altitude", "Rubicon", "Rubicon 392", "4xe"],
    "Wrangler JK": ["Sport", "Sahara", "Rubicon"],
  },
  KIA: {
    Carnival: ["LX", "LX+", "EX", "SX", "SX-L"],
    EV6: ["Standard Range", "Long Range", "GT-Line", "GT"],
    EV9: ["Light", "Wind", "Land", "GT-Line"],
    Forte: ["LX", "EX", "EX+", "EX Premium", "GT-Line", "GT"],
    K5: ["GT-Line", "EX", "GT"],
    Niro: ["LX", "EX", "EX Premium", "SX Touring", "EV"],
    Optima: ["LX", "EX", "SX", "SXL"],
    Rio: ["LX", "LX+", "EX", "EX Premium"],
    Rondo: ["LX", "EX", "EX Luxury"],
    Sedona: ["L", "LX", "EX", "SX", "SXL"],
    Seltos: ["LX", "EX", "EX Premium", "SX Turbo"],
    Sorento: ["LX", "LX+", "EX", "EX+", "SX", "X-Line", "Hybrid", "Plug-in Hybrid"],
    Soul: ["LX", "EX", "EX+", "GT-Line", "EV"],
    Sportage: ["LX", "EX", "EX Premium", "SX", "X-Line", "X-Pro", "Hybrid", "Plug-in Hybrid"],
    Stinger: ["GT-Line", "GT", "GT Limited"],
    Telluride: ["EX", "SX", "SX Limited", "X-Line", "X-Pro"],
  },
  MAZDA: {
    "CX-3": ["GX", "GS", "GT"],
    "CX-30": ["GX", "GS", "GT", "GT Turbo"],
    "CX-5": ["GX", "GS", "GT", "Kuro", "Signature", "Sport Design"],
    "CX-50": ["GS-L", "GT", "GT Turbo", "Meridian", "Hybrid"],
    "CX-70": ["GS-L", "GT", "Signature", "PHEV"],
    "CX-9": ["GS", "GS-L", "GT", "Signature", "Kuro"],
    "CX-90": ["GS", "GS-L", "GT", "Signature", "PHEV"],
    Mazda3: ["GX", "GS", "GT", "GT Turbo", "Sport"],
    Mazda5: ["GS", "GT"],
    Mazda6: ["GX", "GS", "GS-L", "GT", "Signature", "Kuro"],
    "MX-5": ["GS", "GS-P", "GT", "RF"],
  },
  MITSUBISHI: {
    "Eclipse Cross": ["ES", "SE", "SEL", "GT"],
    Lancer: ["DE", "ES", "SE", "GTS", "Ralliart"],
    Mirage: ["ES", "SE", "GT", "LE"],
    "Mirage G4": ["ES", "SE"],
    Outlander: ["ES", "SE", "LE", "SEL", "GT", "PHEV"],
    RVR: ["ES", "SE", "SEL", "LE", "GT"],
  },
  NISSAN: {
    Altima: ["S", "SV", "SR", "SL", "Platinum"],
    Frontier: ["S", "SV", "PRO-4X", "Pro-4X Luxury"],
    Kicks: ["S", "SV", "SR"],
    Leaf: ["S", "SV", "S Plus", "SV Plus", "SL Plus"],
    Maxima: ["SV", "SR", "Platinum"],
    Micra: ["S", "SV", "SR"],
    Murano: ["S", "SV", "SL", "Platinum", "Midnight"],
    Pathfinder: ["S", "SV", "SL", "Platinum", "Rock Creek"],
    Qashqai: ["S", "SV", "SL"],
    Rogue: ["S", "SV", "SL", "Platinum", "Rock Creek"],
    "Rogue Sport": ["S", "SV", "SL"],
    Sentra: ["S", "SV", "SR", "SL"],
    Titan: ["S", "SV", "PRO-4X", "SL", "Platinum Reserve"],
    Versa: ["S", "SV", "SR"],
    "Versa Note": ["S", "SV", "SR", "SL"],
  },
  RAM: {
    1500: ["Tradesman", "Big Horn", "Sport", "Rebel", "Laramie", "Limited", "Longhorn", "TRX", "RHO", "Warlock", "Classic"],
    2500: ["Tradesman", "Big Horn", "Power Wagon", "Laramie", "Limited", "Longhorn"],
    3500: ["Tradesman", "Big Horn", "Laramie", "Limited", "Longhorn"],
    "ProMaster 1500": ["Cargo", "Window"],
    "ProMaster 2500": ["Cargo", "Window"],
    "ProMaster 3500": ["Cargo", "Window"],
    "Promaster City": ["Cargo", "Wagon", "SLT"],
  },
  SUBARU: {
    Ascent: ["Convenience", "Touring", "Limited", "Premier", "Onyx"],
    BRZ: ["Base", "Sport-tech", "tS"],
    Crosstrek: ["Convenience", "Touring", "Sport", "Outdoor", "Limited", "Onyx", "Wilderness"],
    Forester: ["Base", "Convenience", "Touring", "Sport", "Wilderness", "Limited", "Premier"],
    Impreza: ["Convenience", "Touring", "Sport", "Sport-tech", "RS"],
    Legacy: ["Convenience", "Touring", "Limited", "GT", "Premier"],
    Outback: ["Convenience", "Touring", "Onyx", "Wilderness", "Limited", "Premier", "Outdoor XT"],
    WRX: ["Base", "Sport", "Sport-tech", "STI"],
  },
  TESLA: {
    "Model 3": ["Standard Range", "Standard Range Plus", "Long Range", "Performance"],
    "Model S": ["Standard", "Long Range", "Plaid", "P100D", "90D", "75D"],
    "Model X": ["Standard", "Long Range", "Plaid", "P100D", "90D", "75D"],
    "Model Y": ["Standard Range", "Long Range", "Performance"],
  },
  TOYOTA: {
    "4Runner": ["SR5", "TRD Off-Road", "TRD Sport", "Limited", "TRD Pro", "Trailhunter", "Platinum"],
    Camry: ["LE", "SE", "XLE", "XSE", "TRD", "Hybrid LE", "Hybrid SE", "Hybrid XLE", "Hybrid XSE"],
    "C-HR": ["XLE", "Limited"],
    Corolla: ["CE", "L", "LE", "S", "SE", "XLE", "XSE", "Hybrid"],
    "Corolla Cross": ["L", "LE", "S", "SE", "XLE", "XSE", "Hybrid"],
    "GR86": ["Base", "Premium"],
    "Grand Highlander": ["XLE", "Limited", "Platinum", "Hybrid"],
    Highlander: ["LE", "XLE", "XSE", "Limited", "Platinum", "Hybrid"],
    Prius: ["Base", "Technology", "XLE", "Limited", "Prime"],
    "Prius C": ["Base", "Technology"],
    "Prius V": ["Base", "Luxury", "Technology"],
    RAV4: ["LE", "XLE", "XLE Premium", "Trail", "Limited", "TRD Off-Road", "Hybrid LE", "Hybrid XLE", "Hybrid XSE", "Hybrid Limited", "Woodland"],
    "RAV4 Prime (PHEV)": ["SE", "XSE", "XSE Technology"],
    Sequoia: ["SR5", "Limited", "Platinum", "TRD Pro", "Capstone"],
    Sienna: ["LE", "XLE", "XSE", "Limited", "Platinum", "Woodland"],
    Tacoma: ["SR", "SR5", "TRD Sport", "TRD Off-Road", "Limited", "TRD Pro", "Trailhunter"],
    Tundra: ["SR", "SR5", "Limited", "Platinum", "1794 Edition", "TRD Pro", "Capstone"],
    Venza: ["LE", "XLE", "Limited"],
    Yaris: ["CE", "LE", "SE", "XLE"],
  },
  VOLKSWAGEN: {
    Atlas: ["Trendline", "Comfortline", "Highline", "Execline", "Peak Edition"],
    "Atlas Cross Sport": ["Comfortline", "Highline", "Execline"],
    Beetle: ["Trendline", "Comfortline", "Highline", "Dune"],
    Golf: ["Trendline", "Comfortline", "Highline", "Sportline"],
    "Golf GTI": ["Base", "Autobahn", "Performance"],
    "Golf R": ["Base"],
    "Golf SportWagen": ["Trendline", "Comfortline", "Highline"],
    GTI: ["Base", "Autobahn", "Performance"],
    "ID.4": ["Standard", "Pro", "Pro S", "Pro S Plus"],
    Jetta: ["Trendline", "Comfortline", "Highline", "Execline", "Sportline", "GLI", "TDI"],
    Passat: ["Trendline", "Comfortline", "Highline", "Execline", "TDI"],
    Taos: ["Trendline", "Comfortline", "Highline"],
    Tiguan: ["Trendline", "Comfortline", "Highline", "R-Line"],
  },
};

// Versions typiques d'une marque quand le modèle précis n'est pas listé
// ci-dessus (souvent des noms de finition partagés par toute la gamme).
const VERSIONS_PAR_MARQUE = {
  ACURA: ["Base", "Premium", "Tech", "A-Spec", "Elite", "Platinum Elite", "Type S"],
  AUDI: ["Komfort", "Progressiv", "Technik", "Premium", "Premium Plus", "Prestige", "S line"],
  BMW: ["Base", "xDrive", "sDrive", "M Sport", "Premium", "Executive"],
  BUICK: ["Base", "Preferred", "Essence", "Sport Touring", "Avenir"],
  CADILLAC: ["Base", "Luxury", "Premium Luxury", "Sport", "Platinum"],
  CHEVROLET: ["LS", "LT", "RS", "Premier", "LTZ", "WT", "Custom", "High Country"],
  CHRYSLER: ["LX", "Touring", "Touring L", "Limited", "Pinnacle"],
  DODGE: ["SE", "SXT", "GT", "R/T", "SRT"],
  FORD: ["S", "SE", "SEL", "Titanium", "XL", "XLT", "Lariat", "Limited", "Platinum", "ST"],
  GENESIS: ["Standard", "Advanced", "Prestige", "Sport"],
  GMC: ["SLE", "SLT", "AT4", "Denali", "Elevation"],
  HONDA: ["DX", "LX", "EX", "EX-L", "Sport", "Touring"],
  HYUNDAI: ["Essential", "Preferred", "Luxury", "Ultimate", "N Line", "GL", "GLS", "Limited"],
  INFINITI: ["Pure", "Luxe", "Essential", "Sensory", "Autograph", "Sport"],
  JAGUAR: ["S", "SE", "HSE", "R-Dynamic", "R"],
  JEEP: ["Sport", "North", "Altitude", "Latitude", "Limited", "Trailhawk", "Overland", "Summit"],
  KIA: ["LX", "EX", "EX Premium", "SX", "GT-Line", "GT", "X-Line"],
  "LAND ROVER": ["S", "SE", "HSE", "Dynamic", "Autobiography"],
  LEXUS: ["Base", "Premium", "Luxury", "F Sport", "Executive"],
  LINCOLN: ["Standard", "Reserve", "Grand Touring", "Black Label"],
  MAZDA: ["GX", "GS", "GS-L", "GT", "Signature", "Kuro"],
  "MERCEDES-BENZ": ["Base", "4MATIC", "AMG Line", "AMG"],
  MINI: ["Classic", "Premier", "Premier+", "Cooper S", "John Cooper Works"],
  MITSUBISHI: ["ES", "SE", "SEL", "LE", "GT"],
  NISSAN: ["S", "SV", "SR", "SL", "Platinum", "PRO-4X"],
  PORSCHE: ["Base", "S", "GTS", "Turbo", "Turbo S", "GT3"],
  RAM: ["Tradesman", "Big Horn", "Sport", "Rebel", "Laramie", "Limited", "Longhorn"],
  SUBARU: ["Convenience", "Touring", "Sport", "Limited", "Premier", "Wilderness"],
  TESLA: ["Standard Range", "Long Range", "Performance", "Plaid"],
  TOYOTA: ["L", "LE", "SE", "XLE", "XSE", "Limited", "Platinum", "TRD"],
  VOLKSWAGEN: ["Trendline", "Comfortline", "Highline", "Execline", "R-Line"],
  VOLVO: ["Core", "Plus", "Ultimate", "Momentum", "Inscription", "R-Design"],
};

// Dernier recours : désignations génériques utiles pour tout véhicule.
const VERSIONS_GENERIQUES = ["Base", "Standard", "Sport", "Luxe", "Limited", "Hybride", "Électrique", "Diesel", "Cabine simple", "Cabine double", "Cabine d'équipe", "Fourgon"];

function versionsPour(marqueCle, modele) {
  const liste = VERSIONS_PAR_MODELE[marqueCle]?.[modele] || VERSIONS_PAR_MARQUE[marqueCle] || VERSIONS_GENERIQUES;
  return [...new Set(liste)];
}

module.exports = { versionsPour };
